### ISSUE TITLE
Passing on maintainership

### ISSUE THREAD

**Issue by withoutboats** [withoutboats/license-exprs#12]
I don't have the time & interest to maintain this crate anymore, it would be awesome to have other people figure out how to distribute maintainership responsibilities.

cc @carols10cents @wking @ltratt

**Comment by wking** [comment]
I'm happy to chip in occasionally, but I have no Rust, so I'm unlikely to be useful for technical issues.

**Comment by ltratt** [comment]
If no-one else wants to do this (@carols10cents ?), I'd be prepared to take on maintainership, although I'd very happily defer to someone else!

**Comment by carols10cents** [comment]
My interest is mostly because crates.io uses license-exprs to validate uploaded crates' licenses, so this crate is important Rust infrastructure. I'm happy to have someone else maintain it, and now that it's under rust-lang-nursery there are more folks who can help manage permissions and such :)

I'm going to create a license-exprs team, invite wking and ltratt to it, and give yinz permissions to maintain this repo :)

**Comment by carols10cents** [comment]
@withoutboats when you have a chance, could you add rust-lang-nursery:cargo and rust-lang-nursery:license-exprs as owners on crates.io?

**Comment by withoutboats** [comment]
added cargo, only a member of a team can add it so i couldnt add license-exprs

**Comment by wking** [comment]
> only a member of a team can add it so i couldnt add license-exprs

That's very strange.  Does the crate owner really have to join a team before they can add the team as a team-owner?  We may need a crates.io admin to get the crate unstuck.

Also, from [the docs][1] it seems like this project will need at least one named owner to manage access.  @carols10cents, would that be you?  I'm also ok with making everybody with write access a named owner of the crate ;).

[1]: https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner

**Comment by wking** [comment]
> We may need a crates.io admin to get the crate unstuck.

Actually, it looks like we need someone with the rust-lang-nursery owner bit (list [here][1]) to unstick this for us.

[1]: https://github.com/orgs/rust-lang-nursery/people?query=role%3Aowner

**Comment by carols10cents** [comment]
@withoutboats I added you to the license-exprs team, sorry about that, so you should be able to add that team as an owner now. You can also/instead add me as a named owner if you want :)

**Comment by Nemo157** [comment]
Any update on maintainership of this repository? I would love to use this library for parsing of licenses in [`cargo-lichking`](https://github.com/Nemo157/cargo-lichking), but at the moment I'm not sure if a PR implementing that (i.e. issue #13) would have anyone to review it.

I'm also more than willing to help maintain this library if you are still looking for more maintainers.

**Comment by wking** [comment]
> … at the moment I'm not sure if a PR implementing that (i.e. issue #13) would have anyone to review it.

I'm happy to review, and I have the commit bit here, but I don't have much Rust experience.

I also still don't have push access to this crate on crates.io, which makes me merging things here not all that useful ;).  @withoutboats, can you run:

```console
$ cargo owner --add carols10cents 
```

or:

```console
$ cargo owner --add wking
```

so one of us becomes a named owner authorized of further crate administration?  Alternatively, can someone with crates.io admin access make that happen directly?

[1]: https://github.com/rust-lang-nursery/license-exprs/issues/12#issuecomment-357023186

**Comment by sunfishcode** [comment]
Any update here? I have a crate I wish to publish with a SPDX 3.1 license, and it appears to be blocked on someone pushing a new version of license-exprs to crates.io.

**Comment by withoutboats** [comment]
I have added the `license-exprs` org as an owner of this crate. So sorry, I thought this was resolved a long time ago!

**Comment by wking** [comment]
> I have added the license-exprs org as an owner of this crate.

That's probably enough for me to be able to push new releases, but we [need a named owner][1] to manage ownership (e.g. if another team should be added or removed later).  @withoutboats, can you make either @carols10cents or myself (or both of us) [a named owner][2]?

[1]: https://github.com/rust-lang-nursery/license-exprs/issues/12#issuecomment-356789810
[2]: https://github.com/rust-lang-nursery/license-exprs/issues/12#issuecomment-383238631

**Comment by withoutboats** [comment]
Added both of you as owners, didn't realize there was a restriction on team owners
