### ISSUE TITLE
License for this package?

### ISSUE THREAD

**Issue by wking** [withoutboats/license-exprs#14]
I'd like to transition from `/` to `AND` or `OR` in our own `Cargo.toml` (compare rust-lang/cargo#4920).  My guess is that the intended license is `MIT OR Apache-2.0` (i.e. “consumers may choose either the MIT terms or the Apache-2.0 terms, at their option”) and not `MIT AND Apache-2.0` (i.e. “consumers must satisfy both the MIT terms and the Apache-2.0 terms”).  `MIT AND Apache-2.0` would seem like a pretty strange choice…

@withoutboats, can you weigh in?  What license expression did you intend?

@breard-r, @ltratt, and @nodakai, you also have commits in master.  Did you have license intentions for those contributions?  Or are you comfortable with whichever of the above @withoutboats intended?

**Comment by withoutboats** [comment]
It was intended to be licensed however crates.io is licensed (since that was the original use case). AFAIK that is `OR`.

**Comment by wking** [comment]
> It was intended to be licensed however crates.io is licensed (since that was the original use case). AFAIK that is `OR`.

`OR` is my guess too, but I've filed rust-lang/crates.io#1225 to get some clarity on it.

**Comment by breard-r** [comment]
According to the [SPDX Specification, appendix IV](https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60), the correct term in this case is `OR`:

> Often a single license can be used to represent the licensing terms of a source code or binary file, but there are situations where a single license identifier is not sufficient. A common example is when software is offered under a choice of one or more licenses (e.g., GPL-2.0 OR BSD-3-Clause). Another example is when a set of licenses is needed to represent a binary program constructed by compiling and linking two (or more) different source files each governed by different licenses (e.g., LGPL-2.1 AND BSD-3-Clause).

**Comment by wking** [comment]
> According to the SPDX Specification, appendix IV, the correct term in this case is `OR`…

I agree that that matches rust-lang/rust's usage.  It's less clear to me that all the contributors *here* intended the `OR` semantics for their contributions.  Since there aren't many contributors here (and they're all still alive, or at least have pushed recent commits to GitHub ;), it seems safest to just ask them all about their intentions.  So far, we have @withoutboats following crates.io (where [at least one contributor intended `OR`][1]) and [you intending `OR`][2].  That leaves @ltratt and @nodakai as the only contributors who haven't chimed in with their intentions.

[1]: https://github.com/rust-lang/crates.io/issues/1225#issuecomment-356384303
[2]: https://github.com/rust-lang-nursery/license-exprs/issues/14#issuecomment-356421093

**Comment by ltratt** [comment]
I'm happy with the proposed change.

**Comment by wking** [comment]
Crates.io is now officially `OR` with rust-lang/crates.io#1226.  So everything is squared away for `OR` except a coment from @nodakai about his intentions for #8.  And that's small enough that I'm willing to claim it uncopyrightable and move ahead with `OR` even without feedback.

**Comment by nodakai** [comment]
@wking Sorry I'm on a trip to Vietnam countryside

I'd be happy to see the change. Please accept this as my agreement that my (tiny) PRs follow the proposed re-licensing
