### ISSUE TITLE
Repository link

### ISSUE THREAD

**Issue by SimonSapin** [withoutboats/license-exprs#2]
https://crates.io/crates/license-exprs currently doesn’t link to this repository, but I see you’ve already added the link ba71da572508be385cffcc3a21279ef91aa09e52. Could you publish a new version with it? Thanks!

**Comment by withoutboats** [comment]
Thanks for reminding me. I had changed my github username between creating the crate and pushing those changes, and couldn't upload to cargo at the time. Then I got busy and it slipped my mind.
