### ISSUE TITLE
Whitelist Apache-2.0 WITH LLVM-exception

### ISSUE THREAD

**Issue by sunfishcode** [withoutboats/license-exprs#21]
The "LLVM Exception" is a new Apache-2.0 relative registered with SPDX. It modifies Apache-2.0 by adding an exception for GPLv2 compatibility, and an exception for compiler output.

It is the license the LLVM project is planning to transition to, and it's an attractive option for other compiler-related projects as well, because of the strengths of the base Apache-2.0 license, the flexibility granted by the exception clauses, the extensive scrutiny it has received by numerous parties involved in the LLVM license change process, and the fact that LLVM itself is expected to use it.

As such, it's desirable for crates.io to accept it as a valid license option.

**Comment by wking** [comment]
[This is in-flight][1] with #19, although I won't be able to push a new release until #12 is resolved.

[1]: https://github.com/rust-lang-nursery/license-exprs/pull/19/files#diff-444eb8f0e7ba956e0e6c6bf35e3849baR402

**Comment by sunfishcode** [comment]
Ok, great. I'll close this issue then, and follow #19.
