### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by sugar700** [withoutboats/license-exprs#27]
Currently libraries and programs using `license-exprs` (well, specifically cargo) cannot use SPDX License List 3.1. Publishing a new version on crates.io would allow to do so.

**Comment by wking** [comment]
> Publishing a new version on crates.io would allow to do so.

This, like #18, is just blocked on #12.  @withoutboats, can you [nominate a new package owner][1]?

[1]: https://github.com/rust-lang-nursery/license-exprs/issues/12#issuecomment-383238631

**Comment by withoutboats** [comment]
The license-exprs team should now own this crate :)
